"""initial

Revision ID: deaa3b802b02
Revises: 
Create Date: 2025-10-16 13:22:26.186187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deaa3b802b02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onderwerp', sa.String(length=250), nullable=True),
    sa.Column('datum_goedkeuring', sa.Date(), nullable=True),
    sa.Column('startdatum', sa.Date(), nullable=True),
    sa.Column('einddatum', sa.Date(), nullable=True),
    sa.Column('beheerscommissie', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan')
    # ### end Alembic commands ###
