"""initial

Revision ID: e110cfe725a6
Revises:
Create Date: 2025-10-20 16:56:49.257077

"""

from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e110cfe725a6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedentries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("actie", sa.String(length=10), nullable=True),
        sa.Column("datum", sa.DateTime(timezone=True), nullable=False),
        sa.Column("onderwerp", sa.String(length=255), nullable=True),
        sa.Column("content", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "plankenmerken",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kenmerk", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plannen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("onderwerp", sa.String(length=250), nullable=True),
        sa.Column("datum_goedkeuring", sa.Date(), nullable=True),
        sa.Column("startdatum", sa.Date(), nullable=True),
        sa.Column("einddatum", sa.Date(), nullable=True),
        sa.Column("beheerscommissie", sa.Boolean(), nullable=True),
        sa.Column(
            "geometrie",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=31370,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.create_index('idx_plannen_geometrie', 'plannen', ['geometrie'], unique=False, postgresql_using='gist')
    op.create_table(
        "relatietypes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("inverse", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "locatie_elementen",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=250), nullable=True),
        sa.Column("resource_object_id", sa.Integer(), nullable=True),
        sa.Column("provincie_niscode", sa.String(), nullable=True),
        sa.Column("provincie_naam", sa.String(length=50), nullable=True),
        sa.Column("gemeente_niscode", sa.String(), nullable=True),
        sa.Column("gemeente_naam", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["resource_object_id"],
            ["plannen.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plannen_bestanden",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("mime", sa.String(length=250), nullable=True),
        sa.Column("naam", sa.String(length=250), nullable=True),
        sa.Column(
            "bestandssoort",
            sa.Enum(
                "BEHEERSPLAN",
                "PLAN",
                "SAMENSTELLING_BEHEERSCOMMISSIE",
                "BIJLAGE",
                "PRVIATE_BIJLAGE",
                "ONOERENDERFGOEDRICHTPLAN",
                "ACTIEPROGRAMMA",
                "EINDRAPPORT",
                "MB",
                name="bestandssoort",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plannen.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plannen_concepten",
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("plan_kenmerk_id", sa.String(length=64), nullable=False),
        sa.Column("concept_uri", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plannen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_kenmerk_id"],
            ["plankenmerken.id"],
        ),
        sa.PrimaryKeyConstraint("plan_id", "plan_kenmerk_id", "concept_uri"),
    )
    op.create_index(
        "plan_scheme_concept_idx",
        "plannen_concepten",
        ["plan_id", "plan_kenmerk_id", "concept_uri"],
        unique=True,
    )
    op.create_table(
        "plannen_erfgoedobjecten",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("erfgoedobject_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plannen.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plannen_statussen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("KLAD", "KLAAR_VOOR_ACTIVATIE", "ACTIEF", name="status"),
            nullable=False,
        ),
        sa.Column("datum", sa.DateTime(timezone=True), nullable=False),
        sa.Column("aanpasser_uri", sa.String(length=255), nullable=False),
        sa.Column("aanpasser_omschrijving", sa.String(length=255), nullable=False),
        sa.Column("opmerkingen", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plannen.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "planrelaties",
        sa.Column("van_id", sa.Integer(), nullable=False),
        sa.Column("relatietype_id", sa.String(length=32), nullable=False),
        sa.Column("naar_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["naar_id"],
            ["plannen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["relatietype_id"],
            ["relatietypes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["van_id"],
            ["plannen.id"],
        ),
        sa.PrimaryKeyConstraint("van_id", "relatietype_id", "naar_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    op.drop_table("planrelaties")
    op.drop_table("plannen_statussen")
    op.drop_table("plannen_erfgoedobjecten")
    op.drop_index("plan_scheme_concept_idx", table_name="plannen_concepten")
    op.drop_table("plannen_concepten")
    op.drop_table("plannen_bestanden")
    op.drop_table("locatie_elementen")
    op.drop_table("relatietypes")
    op.drop_index(
        "idx_plannen_geometrie", table_name="plannen", postgresql_using="gist"
    )
    op.drop_table("plannen")
    op.drop_table("plankenmerken")
    op.drop_table("feedentries")
    # ### end Alembic commands ###
